[[Program_IOPMPs]]
:numbered:
[#SECTION_4]
== Programming IOPMPs
At times, it can be difficult or even impossible to configure all IOPMP settings when the system starts, especially before I/O agents are active or connected to the system. As a result, it is necessary to update IOPMP settings during runtime. This may occur when a device is enabled, disabled, added, removed, or when the accessible area of a device changes. When updating, it is important to avoid checking transactions in an incomplete setting. However, updating IOPMP settings often involves a series of control accesses, and if a transaction check occurs during the update, it can potentially create a vulnerability. 
It could be a heavy burden for the security software to guarantee that no transactions are in progress from all related initiators. This chapter describes an optional method for updating IOPMP's settings that avoids checking transactions in an incomplete setting and burdening the security software.

[#SECTION_4_1]
=== Atomicity Requirement
The Atomicity Requirement is that when updating an IOPMP, all transactions from receiver ports must be checked either before any changes are made or after all changes are completed. Essentially, checking a transaction in a partial setting should be avoided. The succeeding sections will describe the mechanism that helps the security software satisfy this requirement.

[#SECTION_4_2]
=== Programming Steps
The general approach for a security software to the atomicity requirement has three major steps, conceptually described as follows:

** Step 1: Stall the related transactions that the following updates may impact.
** Step 2: Update IOPMP's settings.
** Step 3: Resume the transactions stalled in Step 1.

Stalling a transaction means the IOPMP stops checking its permission until it is resumed. In the meantime, the transaction should wait. For step 1, it might be necessary to verify if the stalling has occurred since some implementations could not immediately stall the desired transactions from receiver ports. Following this, execute the IOPMP updates as step 2, and finally, resume all stalled transactions in step 3.

[NOTE]
====
In some cases, Step 1 and Step 3 may be skipped as long as no transaction check is performed within Step 2. Writing the SRCMD of an RRID is an example because it involves a single write.
====

NOTE: Stalling a transaction could be implemented in the following ways but not limited to: (1) IOPMP may enqueue the transactions to stall but not be checked, (2) ask the transaction initiator to retry the transaction by a retry message, and (3) enqueue first and ask to retry if the queue is full.

[#SECTION_4_3]
=== Stall Transactions
For Step 1, it's possible to postpone all transactions until all updates are finished. However, this could cause unrelated transactions to experience unnecessary delays. This might not be tolerable for devices that require low latency, like a display controller that periodically retrieves a frame from its video buffer. This section explains the mechanism that only stalls specific transactions to prevent the aforementioned scenario and ensure the atomicity requirement. All the features mentioned below are optional.

In Step 2, the decision of whether a transaction should be stalled cannot reference the current settings because these settings are under updating. Therefore, the only reliable information for this decision is the RRID carried by the transaction. To simplify the following descriptions, we use _rrid_stall_ to represent an abstract bit array, where _rrid_stall_[_s_] = 1 indicates that transactions with RRID _s_ must be stalled. The IOPMP stalls a transaction based on its corresponding _rrid_stall_. Please note that it may not be an actual bit array in practice, just for easier expression. Thus, it is not accessible by software.

Register *MDSTALL* and *MDSTALLH* control _rrid_stall_. *MDSTALL.md* and *MDSTALLH.mdh* are used to select MDs. Denote _stall_by_md_ to represent the concatenation of *MDSTALL.mdh* and *MDSTALL.md*. That is, _stall_by_md_[30:0] is *MDSTALL.md[30:0]*, and _stall_by_md_[62:31] is *MDSTALLH.mdh[31:0]* if any. An MD _m_ is selected when _stall_by_md_[_m_] = 1. *MDSTALL.exempt* controls the polarity of the selection. An IOPMP updates _rrid_stall_ only when *MDSTALL.exempt* is written. When *MDSTALL.exempt* is written to 0, _rrid_stall_[_s_] is set if RRID _s_ is associated with a selected MD _m_ (_stall_by_md_[_m_] = 1). The SRCMD table defines the association of RRID _s_ and MD _m_. Conversely, when *MDSTALL.exempt* is written to 1, _rrid_stall_[_s_] must be clear if RRID _s_ is associated with a selected MD. This relation can be formulated as follows:

[.text-center]
`_rrid_stall_[_s_] <= MDSTALL.exempt ^ ( Reduction_OR (SRCMD(_s_).md & _stall_by_md_));`

Where:

* ^ is bitwise logical exclusive OR operator, 
* & is bitwise logical AND operator, and
* Reduction_OR() is a function that applies bitwise logical OR across all input values.

As to <<#SECTION_3_2_3, SRCMD table Format 2>>, *SRCMD(_s_).md[_m_]* in the above equation is: ‘0’ for all unimplemented MD _m_ and ‘1’ for an implemented MD _m_ because every RRID associates all implemented MDs.

For any unimplemented MD, the corresponding bit in *MDSTALL.md* or *MDSTALLH.mdh* should be wired to 0.

_rrid_stall_ should be updated only when *MDSTALL.exempt* is written, that is, when *MDSTALL* is written. When *MDSTALLH* is written, the only action is to hold the value.

NOTE: Although _rrid_stall_ is derived from the SRCMD table, it should be updated only when *MDSTALL.exempt* is written. We cannot use the table when stalling transactions because the table updates may still be in progress when the IOPMP decides if a transaction should be stalled. Writing *MDSTALL* is just like capturing a snapshot of the table at the moment right before updating any settings. The _rrid_stall_ reflects the SRCMD table before any updates. 

NOTE: When writing *MDSTALL*, the specification only defines the transactions with RRID=_s_ must be stalled for all _rrid_stall_[_s_] = 1. It doesn't request the rest of the transactions to stall or not. It only asks that all transactions be resumed when writing *MDSTALL* with a zero.

[#SECTION_4_4]
=== Cherry Pick
Writing *RRIDSCP* register is an optional method after writing *MDSTALL* in Step 1 of <<#SECTION_4_2, Programming Steps>> to pick the transaction with specific RRIDs if *MDSTALL*/*MDSTALLH* doesn't stall all the desired transactions.

[NOTE]
====
*MDSTALL*/*MDSTALLH* only stall the RRIDs based on their original values in the SRCMD table, not their updated values. Therefore, stall behaviors may not fully meet expectations if certain RRIDs are associated with different MDs after programming steps are completed.
====

The *RRIDSCP* register comprises two fields: a 2-bit *RRIDSCP.op* and a field for *RRIDSCP.rrid*. By setting *RRIDSCP.op* = 1, the _rrid_stall_[_s_] is activated for _s_ = *RRIDSCP.rrid*. Conversely, by setting *RRIDSCP.op* = 2, the _rrid_stall_[_s_] is deactivated for _s_ = *RRIDSCP.rrid*. This register is used to fine-tune the result of writing *MDSTALL*/*MDSTALLH*. The value of *RRIDSCP.op* = 0 is to query the _rrid_stall_ indirectly, and the value of 3 is reserved.

[#SECTION_4_5]
[#FAULTING_STALLED_TRANSACTIONS]
=== Faulting stalled transactions
Faulting stalled transactions can be allowed. To allow faulting over stalling when an IOPMP cannot accommodate more stalled transactions, such as when the receiver port lacks a buffer for transaction storage, set *ERR_CFG.stall_violation_en* to 1 before Step 1 of <<#SECTION_4_2, Programming Steps>>. If any transaction is faulted due to the stalled transactions, the error information shall be logged in *ERR_REQINFO*, where *ERR_REQINFO.etype* = 0x07 (error due to stalled transactions). The procedure for faulting checking transactions is identical to Steps 1-3 of <<#SECTION_4_2, Programming Steps>>, except that, besides stalling and delaying the transactions, transactions can be faulted and cannot be resumed if the IOPMP can't handle more stalled transactions.

[NOTE]
====
In certain implementations, rather than stalling the related transactions, the system may opt to fault the checking transactions during an IOPMP atomic update. Faulting transactions can be advantageous if the system lacks sufficient buffer capacity to record and store all transactions during the IOPMP programming process.

This function also can prevent the risk of deadlock in some systems. If an implementation or a system doesn't have sufficient buffer capacity for handling all stalled transactions during programming, the stalled transactions may backpressure from receiver port of the IOPMP and then occur hang on the port due to its implementation limitation. Therefore, the hang on the port potentially causes a deadlock in the system since transactions for programming IOPMP during Step 2 and Step 3 have the possibility to hang indirectly in the circumstance. 
====

[#SECTION_4_6]
=== Resume Stall

In order to resume all stalled transactions, the IOPMP can be prompted by writing 0 to *MDSTALL*. This corresponds to Step 3 of <<#SECTION_4_2, Programming Steps>>.  After *MDSTALL* is written by zero, an IOPMP should de-assert *MDSTALL.is_stalled* within some time, at which point all transactions have been resumed.

[#SECTION_4_7]
=== The Order to Stall
In Step 1 of <<#SECTION_4_2, Programming Steps>>, *MDSTALL* can be written at most once and before any *RRIDSCP* is written. After a resume, writing a non-zero value to *MDSTALL* multiple times leads to stall feature having an undefined behavior.

*RRIDSCP* can be written multiple times or not at all.

An IOPMP requests stalls after *MDSTALL* and *RRIDSCP* are written. The requested stalls may not take effect at same time. To determine whether all requested stalls take effect, one can read back the bit *MDSTALL.is_stalled*, which is in the same location as *MDSTALL.exempt* on a write. *is_stalled* = 1 indicates all requested stalls taking effect. A new write to *RRIDSCP* may temporarily reset *is_stalled* to 0 if it was previously set to 1, until all requested stalls take effect.

[NOTE]
====
After writing any non-zero value to *MDSTALL*, *MDSTALL.is_stalled* must be asserted, regardless of whether any RRID is stalled. A delay in the assertion is permissible. The software polling the status bit doesn't need to consider whether any RRID will be stalled. On the other hand, after writing zero to *MDSTALLH* (if any) and then *MDSTALL*, *MDSTALL.is_stalled* must be de-asserted. A delay in the de-assertion is permissible.
====

Based on <<#SECTION_4_2, Programming Steps>>, complete steps to program an IOPMP should be followed.

** Step 1.1: write *MDSTALL* once // exactly once
** Step 1.2: write *RRIDSCP* zero or more times
** Step 1.3: poll until *MDSTALL.is_stalled* == 1 // to ensure all stalls takes effect
** Step 2: update IOPMP's settings
** Step 3.1: write *MDSTALL* = 0 // resume all transactions
** Step 3.2: poll until *MDSTALL.is_stalled* == 0  // optional, to ensure all resumes take effect. 

Some steps may be skipped according to the actual implementation.


To query if all transactions associated with a specific RRID are stalled, do the following. First, write 0 to *RRIDSCP.op* and the RRID you want to query to *RRIDSCP.rrid*. Then, read back *RRIDSCP*. The readback of *RRIDSCP.stat* = 1 means that transactions with the queried RRID have stalled, that is, the corresponding bit in _rrid_stall_ is 1. If the value is 2, it means they are not stalled. A value of 3 indicates an unimplemented or unselectable RRID in *RRIDSCP.rrid*. *RRIDSCP.stat* is in the same location as *RRIDSCP.op* on a write. *RRIDSCP.rrid* should keep the last written legal RRID and *RRIDSCP.stat* reflects the current state of this RRID. This method is considered an indirect way to read _rrid_stall_.

[#SECTION_4_8]
=== Implementation Options
All registers described in this chapter are optional. Moreover, these features could be partially implemented. In *MDSTALL.md* and *MDSTALLH.mdh*, not every bit should be implemented even though the corresponding MD is implemented. An unimplemented bit means unselectable and should be wired to zero. To test which bits are implemented, one can write all 1's to *MDSTALL.md* and *MDSTALLH.mdh* and then read them back. An implemented bit returns 1.

If an IOPMP implementation has fewer than 32 memory domains, *MDSTALLH* should be wired to zero.

NOTE: An example of partial implementation of *MDSTALL.md*/*MDSTALLH.mdh* is a system with a display controller, which is a latency-sensitive device. On updating the IOPMP, the transactions initiated from the display controller should not be stalled. Thus, one can always use *MDSTALL.exempt*=1 and *MDSTALL.md[_j_]*=1, where MD _j_ is the memory domain for the frame buffer that the display controller keeps accessing. Thus, the system only needs to implement *MDSTALL.md[_j_]*.

If whole *MDSTALL* is not implemented, *MDSTALL*, *MDSTALLH* and *ERR_CFG.stall_violation_en* should always return zero.

If *RRIDSCP* is not implemented, it always returns zero. One can test if it is implemented by writing a zero and then reading it back. Any IOPMP implementing *RRIDSCP* should not return a zero in *RRIDSCP.stat* in this case.

It is unnecessary to allow every implemented RRID to be selectable by *RRIDSCP.rrid*. If an unimplemented or unselectable RRID is written into *RRIDSCP.rrid*, it returns *RRIDSCP.stat* = 3.

*ERR_CFG.stall_violation_en* is a WARL field so it can be programmable or fixed.
