[[Program_IOPMPs]]
:numbered:
== Programming IOPMPs
At times, it can be difficult or even impossible to configure all IOPMP settings when the system starts, especially before I/O agents are active or connected to the system. As a result, it is necessary to update IOPMP settings during runtime. This may occur when a device is enabled, disabled, added, removed, or when the accessible area of a device changes. When updating, it is important to avoid putting IOPMP in a transient metastable state due to incomplete settings. However, updating IOPMP settings often involves a series of control accesses, and if a transaction check occurs during the update, it can potentially create a vulnerability. 
It can be difficult for the security software to guarantee that no transactions are in progress from all related initiators. A false alarm could result in significant performance issues. This chapter describes an optional method for updating IOPMP's settings without intervening transaction initiators.

=== Atomicity Requirement
The term here "stable" refers to meeting the atomicity requirement. This implies that when updating an IOPMP, all transactions from input ports must be checked either before any changes or after completing all changes. Essentially, using partial settings in an IOPMP should be avoided. The succeeding sections will describe the mechanism to satisfy this requirement.

=== Programming Steps
The general approach to the atomicity requirement has three major steps, conceptually described as follows:

** Step 1: Stall related transactions. Before proceeding with any updates, delay checking the transactions that may be impacted. 
** Step 2: Update IOPMP's settings.
** Step 3: Resume stalled transactions. 

For step 1, it's important to verify if the necessary stalling transactions have taken place since they might not be instantaneous in certain implementations. Following this, execute the IOPMP update as step 2, and finally, resume all stalled transactions in step 3.

[NOTE]
====
In some cases, Step 1 and Step 3 may be skipped as long as no transaction check can interrupt Step 2. Updating MDs associated with a specific SID to other MDs is an example.
====

=== Stall Transactions
For Step 1, it's possible to postpone all transactions until all updates are finished. However, this could cause unrelated transactions to experience unnecessary delays. This might not be tolerable for devices that require low latency, like a display controller that periodically retrieves a frame from its video buffer. This section explains the mechanism that only stalls specific transactions to prevent the aforementioned scenario and ensure the atomicity requirement. All the features mentioned below are optional.

Since the stalls occur when updating is in progress, determining wheater a transaction's check should wait cannot be based on any IOPMP's configuration about to change. Therefore, the only information that can be relied upon for this decision is the SID carried by the transaction. To simplify the following description, we use a conceptual signal called sid_stall[_i_] to indicate whether the transaction with SID=_i_ must wait. Please note that it may not be an actual signal in practice and is not accessible directly for software.

A conceptual internal signal sid_stall has the same number of bits as the SIDs in the IOPMP. sid_stall is generated by the bit MDSTALL.exempt.   stall_by_md is the concatenation of MDSTALL.mdh and MDSTALL.md, that is, stall_by_md[30:0] is MDSTALL.md[31:1] and stall_by_md[62:31] is MDSTALLH.mdh[31:0] if any. When MDSTALL.exempt is zero, any non-zero value in stall_by_md[_j_] will cause transactions with SID=_i_ to be stalled for all the SID _i_ associated with the MD _j_. On the contrary, on MDSTALL.exempt=1, checks of all transactions must wait except those with SID=_i_ associated with any MD _j_  and stall_by_md[_j_] = 1. This relation can be more precisely described as follows:

[.text-center]
`sid_stall[_i_] <= MDSTALL.exempt ^ ( Reduction_OR (SRCMD(_i_) & stall_by_md));`

For any unimplemented memory domain, the corresponding bit in MDSTALL.md or MDSTALLh.mdh should be wired to 0.

sid_stall should be captured only when MDSTALL.exempt is written, that is, when MDSTALL is written. When MDSTALLH is written, the only action is to hold the value.

NOTE: Although sid_stall is related to the SRCMD table, but should be captured only when MDSTALL.exempt is written. The behavior of writing MDSTALL is used to capture a momentary snapshot of the table because the table may not be stable during the updating.

=== Cherry Pick
If MDSTALL doesn't stall all the desired transactions, there is an optional method to pick the transaction with specific SIDs. The SIDSCP register comprises two fields: a 2-bit SIDSCP.op and a field for SIDSCP.sid. By setting SIDSCP.op=1, the sid_stall[_i_] is activated for __i__=SIDSCP.sid. Conversely, by setting SIDSCP.op=2, the sid_stall[_i_] is deactivated for _i_=SIDSCP.sid. This register can be considered as the fine-tuning sid_stall after MDSTALL. The value of SIDSCP.op=0 is to query the sid_stall indirectly, and the value of 3 is reserved.

=== Resume Stall
In order to resume all stalled transactions, the IOPMP can be prompted by writing 0 to MDSTALL. This corresponds to Step 3 of the "Programming Steps" section.

=== The Order to Stall
In Step 1 of programming IOPMP, MDSTALL can be written at most once and before any SIDSCP is written. After a resume, writing a non-zero value to MDSTALL multiple times leads to an undefined situation.

SIDSCP can be written multiple times or not at all. To determine whether all requested stalls take effect, one can read back the bit MDSTALL.is_stalled, which is in the same location as MDSTALL.exempt on a write. MDSTALL.is_stalled=1 indicates all requested stalls taking effect.

To query if all transactions associated with a specific SID are stalled, do the following. First, write 0 to SIDSCP.op and the SID you want to query to SIDSCP.sid. Then, read back SIDSCP. The readback of SIDSCP.stat = 1 means that transactions with the queried SID have stalled, that is, the corresponding bit in sid_stall is 1. If the value is 2, it means they are not stalled. A value of 3 indicates an unimplemented or unselectable SID in SIDSCP.sid. SIDSCP.stat is in the same location as SIDSCP.op on a write. SIDSCP.sid should keep the last written legal SID and SIDSCP.stat reflects the current state of this SID. This method is considered an indirect way to read sid_stall.

=== Implementation-Dependent
All registers described in this chapter are optional. Moreover, these features could be partially implemented. In MDSTALL.md and MDSTALLH.mdh, not every bit should be implemented even though the corresponding MD is implemented. An unimplemented bit means unselectable and should be wired to zero. To test which bits are implemented, one can write all 1's to MDSTALL.md and MDSTALLH.mdh and then read them back. An implemented bit returns 1.

If an IOPMP implementation has fewer than 32 memory domains, MDSTALLH should be wired to zero.

NOTE: An example of partial implementation of MDSTALL.md/MDSTALLH.mdh is a system with a display controller, which is a latency-sensitive device. On updating the IOPMP, the transactions initiated from the display controller should not be stalled. Thus, one can always use MDSTALL.exempt=1 and MDSTALL.md[_j_]=1, where MD _j_ is the memory domain for the frame buffer that the display controller keeps accessing. Thus, the system only needs to implement MDSTALL.md[_j_].

If the whole MDSTALL is not implemented, MDSTALL and MDSTALLH should always return zero.

If SIDSCP is not implemented, it always returns zero. One can test if it is implemented by writing a zero and then reading it back. Any IOPMP implementing SIDSCP should not return a zero in SIDSCP.stat in this case.

It is unnecessary to allow every implemented SID to be selectable by SIDSCP.sid. If an unimplemented or unselectable SID is written into SIDSCP.sid, it returns SIDSCP.stat = 3.
