[#NON_PRIORITY_ENTRIES]
=== Non-priority IOPMP entries

The extension enables non-priority entries to reduce latency, power consumption, and area. It can also be used together with the priority entries to achieve a balance between security and performance.

When the extension is enabled, entries with indices greater than or equal to *HWCFG2.prio_entry* are non-prioritized. These are treated equally and assigned the lowest priority. Entries with indices less than *prio_entry* are prioritized. The value of *prio_entry* is implementation-dependent. Additionally, a field *HWCFG2.prient_prog* indicates whether *prio_entry* is programmable.

[NOTE]
====
Priority entries safeguard the most sensitive data, even in the event of secure software being compromised. However, implementing a large number of priority entries results in higher latency and increased area usage. In contrast,non-priority entries are treated equally and can be cached in smaller numbers. A mix of entry types provides flexibility in balancing security and performance.
====

An entry qualifies as a matching entry with the extension for an incoming transaction if:

* For priority entries, its region covers any byte of the transaction,
* For non-priority entries, its region covers all bytes of the transaction,
* It is associated with the RRID carried by the transaction; and
* It holds the highest priority among entries that meet the previous criteria.

[NOTE]
====
Multiple matching entries are allowed for non-priority entries because they share the lowest priority.
====

[NOTE]
====
IOPMPs don't report error type = 0x04 "Partial hit on a priority rule" on non-priority entries because non-priority entries must covers all bytes of the transaction.
====

If one matching entry is priority, the reaction is the same as baseline IOPMP entry array.

If one matching entry is non-priority, the transaction is legal if any matching entry permits its access type. If no matching entry permits, the transaction is illegal with error type = "illegal read access" (0x01) for read access transaction or "illegal write access/AMO" (0x02) for write access/AMO transaction. If an IOPMP supports instruction fetch permission check (*HWCFG0.chk_x* = 1), the IOPMP reports illegal instruction fetch transaction with with error type = "illegal instruction fetch" (0x03).

For an illegal transaction matching multiple non-priority entries, if the interrupt is triggered or the bus error response is returned, *ERR_REQID.eid* stores the index of any of them.

[cols="<2,<1,<1,<1,<6"]
|===
5+h|HWCFG0{set:cellbgcolor:#D3D3D3}
5+h|0x0008
h|Field                         |Bits   |R/W    |Default    |Description
|{set:cellbgcolor:#FFFFFF}
prient_prog                     |7:7    |W1CS   |IMP        |A write-1-clear bit is sticky to 0 and indicates if *HWCFG2.prio_entry* is programmable. Reset to 1 if the implementation supports programmable *prio_entry*, otherwise, wired to 0.
|===

[cols="<2,<1,<1,<1,<6"]
|===
5+h|HWCFG2{set:cellbgcolor:#D3D3D3}
5+h|0x0010
h|Field                         |Bits   |R/W    |Default    |Description
|{set:cellbgcolor:#FFFFFF}
prio_entry                      |15:0   |WARL   |IMP        |Indicate the number of entries matched with priority. These rules should be placed in the lowest order. Within these rules, the lower order has a higher priority.
|===