=== Data Only Devices and Buses

IOPMPs may only protect from data only device such as general DMA.
The IOPMP under the general DMA in <<IOPMP_SE_Example>> illustrates an example integration.
In this scenario, instruction fetch permission checking is not required.
Therefore, all permission bits related to instruction fetch (`x` in `ENTRY_CFG`, and `SRCMD_X`/`SRCMD_XH` of <<#SPS_EXT,SPS extension>>) can be fixed to 0, or not implemented.

For some small-scale systems which have a single RISC-V hart with PMP and data-only bus initiators,
or for some system buses that don't provide any instruction fetch hint,
the IOPMP can treat the instruction fetch accesses as data read accesses.
This simplifies both the system and IOPMP configuration by fixing all instruction fetch permission bits to 0, or making them unavailable.
The field `HWCFG3.xinr` indicates whether the IOPMP data read permission treats the instruction fetch accesses as data read accesses.

[NOTE]
====
A system with a single RISC-V hart that includes PMP and data-only bus initiators can enforce execution permission checking entirely within the hart using its PMP.
Consequently, the system bus in such a configuration only needs to support general read and write accesses.
====

[cols="<2,<1,<1,<1,<6"]
|===
5+h|HWCFG3{set:cellbgcolor:#D3D3D3}
5+h|0x0014
h|Field |Bits |R/W |Default |Description
|{set:cellbgcolor:#FFFFFF} `xinr` |11:11 |R |IMP a|Indicates whether the IOPMP treats the instruction fetch accesses as data read accesses.
All instruction fetch permission bits of the IOPMP can be fixed to 0, or unavailable.
|===