=== Data Only Devices and Buses

IOPMPs may only protect from data only device such as general DMA.
The IOPMP under the general DMA in <<IOPMP_SE_Example>> illustrates an example integration.
In this scenario, instruction fetch permission checking is not required.
Therefore, all fields related to instruction fetch can be fixed to 0, or not implemented.
This can apply to `x` in `ENTRY_CFG`, `sixe`/`sexe` of <<#PEIS_PEES,Per-entry Interrupt/Bus Error Suppression>> in `ENTRY_CFG`, and `SRCMD_X`/`SRCMD_XH` of <<#SPS_EXT,SPS extension>>.

For some small-scale systems which have a single RISC-V hart with PMP and data-only requesters,
or for some system buses that don't provide any instruction fetch hint,
the IOPMP can treat the instruction fetch accesses as data read accesses.
This simplifies both the system and IOPMP configuration by fixing all instruction fetch permission bits to 0, or making them unavailable.
The field `xinr` in register `HWCFG3` (<<#REG_EXT_HWCFG3,Hardware Configuration 3>>) indicates whether the IOPMP treats the instruction fetch accesses as data read accesses.

[NOTE]
====
A system with a single RISC-V hart that includes PMP and data-only requesters can enforce execution permission checking entirely within the hart using its PMP.
Consequently, the system bus in such a configuration only needs to support general read and write accesses.
====