[#mdcfg-table-formats]
=== MDCFG Table Reduction

Users can reduce MDCFG table that best fits their design requirements, such as area, power consumption, latency, throughput. The section provides a suggestion to reduce MDCFG table.

==== Each Memory Domain Has Exactly _k_ Entries
Each memory domain has exactly _k_ entries, where _k_ is implementation-dependent and non-programmable. The MDCFG table and the register *MDCFGLCK* can be omitted. The value of the read-only field *HWCFG3.md_entry_num* is the _k_ value minus 1. 

[NOTE]
====
_k_ * *HWCFG0.md_num* can be greater than *HWCFG1.num_entry*. Behavior of any entry with index &#8805; *HWCFG1.num_entry* is described on <<#IOPMP_ENTRY, IOPMP Entry and IOPMP Entry Array>>.
====

For a particular case of _k_=1 (*HWCFG3.md_entry_num*=0), every memory domain has exactly one entry. One can skip the concept of the memory domain when using such an IOPMP.

The _k_ value also can be programmable. Users can use *HWCFG0.enable* as the lock bit of *HWCFG3.md_entry_num*.

To indicate the reduced table, one can use *HWCFG3.mdcfg_fmt* to indicate what reduced table format is implemented in an IOPMP.
