=== MDCFG Table Reduction

Users can reduce MDCFG table that best fits their design requirements, such as area, power consumption, latency, throughput. The section provides a suggestion to reduce MDCFG table.

==== Each Memory Domain Has Exactly _k_ Entries
Each memory domain has exactly _k_ entries, where _k_ is implementation-dependent and non-programmable. The MDCFG table and the register *MDCFGLCK* can be omitted. To read the _k_ value, <<#TABLE_MDCFG_REDUCTION>> is a reference. The value of the read-only field *md_entry_num* is the _k_ value minus 1. 

[NOTE]
====
_k_ * *HWCFG0.md_num* can be greater than *HWCFG1.num_entry*. Behavior of any entry with index &#8805; *HWCFG1.num_entry* is described on <<#IOPMP_ENTRY, IOPMP Entry and IOPMP Entry Array>>.
====

For a particular case of _k_=1 (*md_entry_num*=0), every memory domain has exactly one entry. One can skip the concept of the memory domain when using such an IOPMP.

The _k_ value also can be programmable. Users can use *HWCFG0.enable* as the lock bit of *md_entry_num*.

[#TABLE_MDCFG_REDUCTION]
[caption="{table-caption} {counter:application-note-table-number}. "]
.A reference for reading the k value
[cols="<2,<2,<6"]
|===
| Field name     | Field width | Description 
| md_entry_num   | 1 to 16     | *md_entry_num* indicates each memory
domain exactly has _k_ (*md_entry_num* + 1) entries in a memory domain.

If *md_entry_num* is programmable, *md_entry_num* is locked if *HWCFG0.enable* is 1.
|===