[#mdcfg-table-formats]
=== MDCFG Table Reduction
In the baseline specification, a complete IOPMP check involves a sequential, two-stage lookup: first the SRCMD Table (to find MD indexes) and then the MDCFG Table (to find the corresponding entry indexes). This data dependency on the MDCFG Table lookup can introduce a latency.

This application note provides a guideline for an optimized implementation model that **eliminates this second lookup stage**. This optimization reduces check latency, simplifies hardware logic, and saves area by removing the need for the MDCFG Table storage.

==== Each Memory Domain Has Exactly _k_ Entries

This format is the foundational mechanism for achieving the optimization described in A.5, and it is the basis for the models in A.7.2 ("Rapid-k Model") and A.7.5 ("Compact-k Model"). The primary motivation is to *remove the MDCFG Table and its associated lookup latency*.

This is achieved by defining that each memory domain contains exactly _k_ entries, where _k_ is a fixed value (e.g., `(HWCFG3.md_entry_num + 1)`). By making _k_ a constant, the range of entry indexes for a given `MD m` is no longer stored in a table but is *directly calculable* (e.g., `Entry Indexes = [m * k, (m * k) + k - 1]`).

This optimization breaks the sequential data dependency of the two-stage lookup, enabling a faster, simpler, and lower-area implementation. Implementations adopting this model can omit the MDCFG Table and the MDCFGLCK register entirely.

[NOTE]
====
_k_ * *HWCFG0.md_num* can be greater than *HWCFG1.num_entry*. Behavior of any entry with index &#8805; *HWCFG1.num_entry* is described on <<#IOPMP_ENTRY, IOPMP Entry and IOPMP Entry Array>>.
====

For a particular case of _k_=1 (*HWCFG3.md_entry_num*=0), every memory domain has exactly one entry. One can skip the concept of the memory domain when using such an IOPMP.

The _k_ value also can be programmable. Users can use *HWCFG0.enable* as the lock bit of *HWCFG3.md_entry_num*.

To indicate the reduced table, one can use *HWCFG3.mdcfg_fmt* to indicate what reduced table format is implemented in an IOPMP.
