=== MDCFG Table Reduction

Users can reduce MDCFG table that best fits their design requirements, such as area, power consumption, latency, throughput. The section provides a suggestion to reduce MDCFG table.

==== Each Memory Domain Has Exactly _k_ Entries
Each memory domain has exactly _k_ entries, where _k_ is implementation-dependent and non-programmable. The MDCFG table and the register *MDCFGLCK* can be omitted. To read the _k_ value, <<#TABLE_MDCFG_REDUCTION>> is a reference. The value of the read-only field *HWCFG0.md_entry_num* is the _k_ value minus 1. 

[NOTE]
====
_k_ * *HWCFG0.md_num* can be greater than *HWCFG1.num_entry*. Behavior of any entry with index &#8805; *HWCFG1.num_entry* is described on <<#IOPMP_ENTRY, IOPMP Entry and IOPMP Entry Array>>.
====

For a particular case of _k_=1 (*HWCFG0.md_entry_num*=0), every memory domain has exactly one entry. One can skip the concept of the memory domain when using such an IOPMP.

The _k_ value also can be programmable. Users can use *HWCFG0.enable* as the lock bit of *HWCFG0.md_entry_num*.

To indicate the reduced table, one can use *HWCFG0.mdcfg_fmt* to indicate what reduced table format is implemented in an IOPMP.

[#TABLE_MDCFG_REDUCTION]
[caption="{table-caption} {counter:application-note-table-number}. "]
.A reference for reducing MDCFG table
[cols="<2,<1,<1,<1,<6"]
|===
5+h|HWCFG0{set:cellbgcolor:#D3D3D3}
5+h|0x0008
h|Field                         |Bits   |R/W    |Default    |Description
|{set:cellbgcolor:#FFFFFF}mdcfg_fmt |1:0    |R      |IMP        a|Indicate the MDCFG format

* 0x0: MDCFG Table is implemented.

* 0x1: No MDCFG Table. *HWCFG.md_entry_num* is fixed.

* 0x2: No MDCFG Table. *HWCFG.md_entry_num* is programmable.

* 0x3: reserved.

|md_entry_num   |23:17  |WARL   |IMP     a| When *HWCFG0.mdcfg_fmt* = 

* 0x0: must be zero

* 0x1 or 0x2: *md_entry_num* indicates each memory domain exactly has (*md_entry_num* + 1) entries in a memory domain


*md_entry_num* is locked if *HWCFG0.enable* is 1.
|===
