#!/usr/bin/env bash

function usage()
{
        cat <<EOF >&2
Usage:  $0 [options]

Options:
     -h                   Display usage
     -l <variable_list>   List of variables in the array
EOF
        exit 1;
}

# Command line options
VAR_LIST=""

while getopts "hi:l:" o; do
        case "${o}" in
        h)
                usage
                ;;
        l)
                VAR_LIST=${OPTARG}
                ;;
        *)
                usage
                ;;
        esac
done
shift $((OPTIND-1))

if [ -z "${VAR_LIST}" ]; then
        echo "The list of variables file should be present"
        usage
fi

awk -v "SCRIPT_NAME=`basename $0`" -v"VARLIST=${VAR_LIST}" '
function array_length(a)
{
    result = 0

    for (i in a)
        result++

    return result
}

BEGIN {
    split(VARLIST,VAR_LIST," ")

    if (array_length(VAR_LIST) == 0) {
        print "Must specify variable list on command line"  > "/dev/stderr"
        exit 1
    }

    printf "/*\n"
    printf " * This file is generated by %s\n", SCRIPT_NAME
    printf " * Please do not edit this file.\n"
    printf " */\n"
    printf "\n"
    printf "#include <iopmp_drv_common.h>\n\n"

    for (v in VAR_LIST) {
        printf("extern const struct iopmp_driver %s;\n", VAR_LIST[v])
    }
    print ""

    printf "const struct iopmp_driver *const iopmp_drivers[] = {\n"
    for (v in VAR_LIST) {
        printf("\t&%s,\n", VAR_LIST[v])
    }
    printf("\tNULL\n");

    printf("};\n");
}
'
